### ISSUE TITLE
Question: Is there a way to only allow users to certain folders when web-term starts?

### ISSUE THREAD

**Issue by misterzik** [IonicaBizau/web-term#23]
Good Afternoon,

I was wondering if there is a way to only allow public users to navigate certain folders when web-term starts?

or perhaps only allow the public user to ssh to a server before using web-term/navigate ?
I believe it's unsafe to leave the web-term box open for all users to navigate.

Best Regards,
Nick

**Comment by IonicaBizau** [comment]
In fact, this is Linux configuration and login management issue–an idea could be to have two Linux users: one for public and another one for private. Then you can configure the folder access based on these users. :sparkle:

**Comment by IonicaBizau** [comment]
In fact, this is Linux configuration and login management issue–an idea could be to have two Linux users: one for public and another one for private. Then you can configure the folder access based on these users. :sparkle:

**Comment by IonicaBizau** [comment]
In fact, this is Linux configuration and login management issue–an idea could be to have two Linux users: one for public and another one for private. Then you can configure the folder access based on these users. :sparkle:

**Comment by IonicaBizau** [comment]
In fact, this is Linux configuration and login management issue–an
idea could be to have two Linux users: one for public and another one
for private. Then you can configure the folder access based on these
users. :sparkle:
