### ISSUE TITLE
Prompt goes past bottom of screen

### ISSUE THREAD

**Issue by scribe** [IonicaBizau/web-term#25]
Hello,

I'm not certain if this is a bug or a user error, but I couldn't find an issue like this.

When using recent versions of chrome the bottom lines of the terminal will always be slightly below the bottom of the window.

To reproduce: Start web-term then hit return until the prompt goes off the bottom of the screen in Chrome 46.

Thank you for your time.

**Comment by IonicaBizau** [comment]
Thanks for the report @scribe!

Can you tell me what font do you use? It is Monaco or something like that?
I can reproduce it on my notebook where I use Monaco as monospace font, but not on my desktop (where `monospace` is used).

@lcristianiim Is it possible to compute the height of the terminal _in the good way_? :smile:

**Comment by lcristianiim** [comment]
I'll check it out

**Comment by lcristianiim** [comment]
@scribe I've failed to reproduce the bug you reported. I have tried it with Chrome 46.0.2490.71 and everything is nice and smooth.
Please verify the font you are using as IonicaBizau suggested and let us know.

**Comment by IonicaBizau** [comment]
@lcristianiim Try to [install the `Monaco` font](https://github.com/cstrap/monaco-font/issues/9#issuecomment-87725915). You will be able to reproduce it. We anyway need to debug this in jillix internal app. :smile:

**Comment by IonicaBizau** [comment]
:ship: **`4.1.0`** :tada:

**Comment by scribe** [comment]
@lcristianiim I was using Times, however the 4.1.0 patch has fixed the issue for me.

Thank you again for your help!

**Comment by IonicaBizau** [comment]
@scribe Awesome! Thanks for feedback! :smile:

**Comment by lcristianiim** [comment]
@scribe As @IonicaBizau said: Awesome! :+1:
