### ISSUE TITLE
terminal lines have a gap

### ISSUE THREAD

**Issue by micimize** [IonicaBizau/web-term#32]
There's a small gap after inline-block `<div/>` lines that makes themes with a background change look bad: 
<img width="326" alt="screen shot 2016-01-04 at 21 18 55" src="https://cloud.githubusercontent.com/assets/8343799/12106812/e4a1f3fe-b328-11e5-8542-21642032fcde.png">

I believe we could fix it with `.terminal > div {display: flex}`, but it'll also require a change to some math somewhere.

**Comment by IonicaBizau** [comment]
Thanks for the report!

What font do you use? When I built it, I guess I tested with `Hack` and `monospace`. :boom:

**Comment by micimize** [comment]
Ah, I guess I'm using `"Monaco", monospace`. If I change the style to `monospace` it looks fine. How is it even getting that font?

**Comment by IonicaBizau** [comment]
@michaeljosephrosenthal Maybe it would be better to use a monospaced Google font which we can be sure it will be the same. Just wondering... :smile:

**Comment by micimize** [comment]
https://github.com/IonicaBizau/web-
Monaco comes from [this style](term/blob/e24e2e4c9d29b88f69bfe8b0941447499ee875f5/bin/public/css/style.css#L9) in the css, but only shows up on my browser because only macs have Monaco. Adding `line-height: 1` also fixes the issue

**Comment by IonicaBizau** [comment]
I have the `Monaco` on my Ubuntu notebook.

I tested out `line-height: 1` and it does fix the problem. :+1: :sparkles: If you like, make a pull request.
