### ISSUE TITLE
expand settings

### ISSUE THREAD

**Issue by micimize** [IonicaBizau/web-term#37]
The settings page is excellent!

I could make a pull request for adding:
1. foreground and background options,
2. add descriptions/notes to the colors (like "this color is typically `cyan`")
3. Add a section for pre-made palettes
4. **bold** as :sparkles:bright:sparkles: checkbox

**Comment by micimize** [comment]
also, right now the default styles contain `font-weight: bold`, so bold doesn't show up. I think that's a different issue though - probably want to really address that with an "add styles" option later.

**Comment by IonicaBizau** [comment]
> foreground and background options,

How can I set them in `term.js`? I guessed they are set using the `colors` array.

> add descriptions/notes to the colors (like "this color is typically cyan")

Can you add more information about this? I'm not sure what you mean.

> Add a section for pre-made palettes

Probably a `<select>` element. :+1: 

> bold as :sparkles:bright:sparkles: checkbox

:+1: 

Glad you like it! :smile:

**Comment by micimize** [comment]
> How can I set them in term.js? I guessed they are set using the colors array.  

you add them as the last two elements in the color array. I thought we should keep them semantically distinct in the configs, so I added `foreground` and `background` attributes to `colors` in #39. 

> Can you add more information about this? I'm not sure what you mean.  

I was just thinking of adding some labels to every color, to describe what the color number is typically used to display in the terminal. I'm not really sure if there's even a convention for that though.

**Comment by micimize** [comment]
closed by #39
