### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by IonicaBizau** [IonicaBizau/web-term#38]
Replace emoji characters with emoji image tags. :joy: That would be a killer feature! :smile:

**Comment by micimize** [comment]
A more general plugin system would be really cool. Eventually users could also define `html`/`css`/`js` widgets that interface with the `web-term` server, and that are included by query string or something.

**Comment by IonicaBizau** [comment]
Agree! :+1: Maybe the plugins can be kept in the config file?

**Comment by IonicaBizau** [comment]
Latest Ubuntu versions support Emoji now. There is no need to replace them with images anymore.
