### ISSUE TITLE
Inheriths caller terminal configuration

### ISSUE THREAD

**Issue by stringparser** [IonicaBizau/web-term#4]
Hey @IonicaBizau, 
reeeally nice project :)

How does it work style-wise, inherits style from the terminal from which web-term was called or there is something special that one would have to do?

I'll check this later today once I get home.

Thanks!

**Comment by IonicaBizau** [comment]
Glad to hear you like this project! :smile: 

It uses [`pty.js`](https://github.com/chjj/pty.js), which creates a bash session on the server, where you can send/receive data via web sockets (between client and server).

**Comment by stringparser** [comment]
Niice! I'm back home now so after dinner I'll take a bite for dessert to `pty.js` :smile_cat:

**Comment by stringparser** [comment]
good work :) I'll close this one
