### ISSUE TITLE
support true color in term.js

### ISSUE THREAD

**Issue by micimize** [IonicaBizau/web-term#40]
[true color](https://gist.github.com/XVilka/8346728) is a spec for sending the full rgb range with every character.

Honestly, while this is something that should be on the road map, I wouldn't call it a priority though.

**Comment by IonicaBizau** [comment]
This would be cool, but this is an issue of term.js, right?

**Comment by micimize** [comment]
Yes, opened this when I though we had committed to diverging.
Opening on their master: chjj/term.js#107
