### ISSUE TITLE
Not opening over aws Ec2

### ISSUE THREAD

**Issue by rtwk** [IonicaBizau/web-term#42]
I am running web-term through another node program as a child process. App runs well, Returns ip:port but when I point my browser to ip:port, which I expect run web term, keeps connecting and finally connection times out. Interestingly though, sometimes, It can connect and behave as expected. 
Security groups in AWS instance shall not be an issue in this case because configured ports to allow there. What am I missing? I have tried to include ip:port to be inserted within iframe of another page, that also fails. Does it not load within iframe?

**Comment by IonicaBizau** [comment]
Not sure how AWS Ec2 handles this, but `web-term` starts a `http` server on `localhost` (unless a custom host is specified using `-H`).

If I have a cloud server where I want to run this, I would probably configure the port using nginx and have a subdomain to my website.

Make sure you can start an http server using node on your machine and then, once you get it working, web-term will probably work too. :smile:

**Comment by rtwk** [comment]
Thanks for suggestions. I did the way you said. I figured it out, it was a typo that caused the problem. But kudos. web-term is great tool to run customized CLI.

**Comment by IonicaBizau** [comment]
@rtwk Glad to hear! :+1: Thanks! :grin:
