### ISSUE TITLE
Change background and font color in style.css not working

### ISSUE THREAD

**Issue by rtwk** [IonicaBizau/web-term#44]
After making changes to style.css file in bin/public/css/style.css, it does not reflect those changes. When it loads, I can see `<div class="terminal">` has inline styles written. May be because of that any relative changes are not taking effect.

**Comment by IonicaBizau** [comment]
@rtwk Thanks for your report! I think you have to change these colors in the `/settings` page. Can you confirm that changing the font and background colors work there? :art:

**Comment by rtwk** [comment]
Well, settings.css does not have any class called terminal.

**Comment by IonicaBizau** [comment]
@rtwk No, open the `localhost:<port>/settings` page. There you should be able to edit the settings.

**Comment by rtwk** [comment]
Yes changes on settings page works. But what if I want to make changes without visiting that page. Is there a way to make such (looks) changes in any file/settings?

**Comment by IonicaBizau** [comment]
@rtwk The settings editable on that page are stored in `~/.web-term.json`. So, you can edit that JSON file. :joy:
