### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by rtwk** [IonicaBizau/web-term#56]
/usr/local/lib/node_modules/web-term/bin/web-term:6
const Lien = require("lien")
^^^^^
SyntaxError: Use of const in strict mode.

Getting this error message. Usually it is recommended to start node with --harmony flag to get rid of this problem. But when web-term is used in command line, there is no scope for using --harmony flag.

**Comment by rtwk** [comment]
Upgrading node from LTS fixed the issue

**Comment by IonicaBizau** [comment]
:+1: 

Glad you fixed it, but you discovered an issue: the files without extension (in this specific case `bin/web-term`) are not babelified: https://github.com/IonicaBizau/babel-it/issues/11
