### ISSUE TITLE
Not working when used as child process

### ISSUE THREAD

**Issue by rtwk** [IonicaBizau/web-term#57]
I was using web-term as child process. And it was working fine. But after updating to the latest version (node v6>), it fails to start web-term as child process. It works when started from terminal directly though.

**Comment by IonicaBizau** [comment]
Just observed the same error. :+1: 

As side effect, the `-d` option is not working too... Help is appreciated!

Other modules are affected and I'm not sure how to solve it...

**Comment by rtwk** [comment]
-d option is working in my case. But no luck with starting it a as a child process.

**Comment by IonicaBizau** [comment]
Interesting! So, after doing `web-term -d -p 9000` are you able to open the `localhost:9000`?

**Comment by rtwk** [comment]
No it is not accessible over http. But the daemon seems to start. At least not throwing any error message. May be you are right. It does not start at all.

**Comment by IonicaBizau** [comment]
Yes, no error, but it fails to start for the same reason. I think it's breaking because of the new version of Node, but don't understand why.

**Comment by rtwk** [comment]
This is very strange. It starts when started from terminal but you call it from nodejs code as a child process and it fails.

**Comment by IonicaBizau** [comment]
Exactly...

**Comment by rtwk** [comment]
Is it because new version of node or because it is rewrite in ES6

**Comment by IonicaBizau** [comment]
It's not because of rewrite. It makes me think it's because of the new Tilda versions (>=4.4.0):

https://github.com/IonicaBizau/tilda

There I added some `process.stdin` things which are related to this behavior....

**Comment by IonicaBizau** [comment]
Confirming it's a bug in Tilda: https://github.com/IonicaBizau/tilda/issues/11

I'm on it.

**Comment by IonicaBizau** [comment]
Isolated this case: http://stackoverflow.com/q/40588859/1420197

**Comment by IonicaBizau** [comment]
@rtwk When you want to start it as child process, use [`spawno`](https://github.com/IonicaBizau/spawno) or specify `stdio: ["inherit"]` in the spawn options.
